# .github/actions/install-poetry/action.yml
name: "Notify on Slack on a pull request review."
description: "Installs a prod environment of Dojo from PyPi"
inputs:
  python-version:
    description: "Python version to use"
    required: true
  repository:
    description: "Name of the Repo"
    required: true
  actor:
    description: "Who created the pull request"
    required: true
  pull_request_url:
    description: "URL to the pull request"
    required: true
  reviewer:
    description: "Who is requested as reviewer"
    required: true
  pull_request_title:
    description: "Title of the pull request"
    required: true


runs:
  using: "composite"
  steps:


    - name: Retrieve secrets from GCP Secrets Manager
      id: get-secrets
      uses: google-github-actions/get-secretmanager-secrets@v2
      with:
        secrets: |
          SLACK_NOTIFYPULLREQUEST_WEBHOOK_URL: projects/557429359617/secrets/slack_notify_webhook_url
    
    - name: Print variables
      run: |
        echo "python-version ${{ inputs.python-version }}"
        echo "repository ${{ inputs.repository }}"
        echo "actor ${{ inputs.actor }}"
        echo "pull_request_url ${{ inputs.pull_request_url }}"
        echo "reviewer ${{ inputs.reviewer }}"
        echo "pull_request_title ${{ inputs.pull_request_title }}"

    - name: Send notification to Slack
      env:
        # SLACK_NOTIFYPULLREQUEST_WEBHOOK_URL: ${{ steps.get-secrets.outputs.SLACK_NOTIFYPULLREQUEST_WEBHOOK_URL }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        GITHUB_ACTOR: ${{ inputs.actor }}
        PULL_REQUEST_URL: ${{ inputs.pull_request_url }}
        REVIEWER: ${{ inputs.reviewer }}
        PULL_REQUEST_TITLE: ${{ inputs.pull_request_title }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{
          "text": "Pull Request Review Requested",
          "attachments": [
            {
              "fallback": "Pull Request <${{ env.PULL_REQUEST_URL }}> requested review by ${{ env.REVIEWER }}",
              "color": "#36a64f",
              "pretext": "A new pull request review has been requested!",
              "title": "${{ env.PULL_REQUEST_TITLE }}",
              "title_link": "${{ env.PULL_REQUEST_URL }}",
              "text": "Repository: ${{ env.GITHUB_REPOSITORY }}\nRequested Reviewer: ${{ env.REVIEWER }}\nBy: ${{ env.GITHUB_ACTOR }}",
              "footer": "GitHub Actions",
              "footer_icon": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
            }
          ]
        }' ${{ steps.get-secrets.outputs.SLACK_NOTIFYPULLREQUEST_WEBHOOK_URL }}

