# .github/actions/install-poetry/action.yml
name: "Dojo PyPi"
description: "Installs a prod environment of Dojo from PyPi"
inputs:
  python-version:
    description: "Python version to use"
    required: true
runs:
  using: "composite"
  steps:

    - name: Print Python version
      shell: bash
      run: |
        echo "Input value: ${{ inputs.python-version }}"

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly

    - name: Install release-executable
      shell: bash
      run: |
        pip install dojo-compass 
