# Setting up a dojo dev environment
name: Setup Dojo dev

on:
  workflow_call:
    inputs:
      python-versin:
        description: 'The version of Python that should be used.'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      python-versin:
        description: 'The version of Python that should be used.'
        required: true
        type: string
    # secrets:
    #   EXAMPLE_SECRET:
    #     required: true

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print Python version
        run: |
          echo "Input value: ${{ inputs.python-version }}"

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-de33b6af53005037b463318d2628b5cfcaf39916 
      
      - name: Install python dependencies on linux
        if: ${{ runner.os == 'linux' }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
          poetry install
          echo "POETRY=poetry" >> $GITHUB_ENV

      - name: Install poetry dependencies on mac
        if: ${{ runner.os == 'macOS' }}
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.4.2
          /Users/runner/.local/bin/poetry install
          echo "POETRY=/Users/runner/.local/bin/poetry" >> $GITHUB_ENV
